src/java/beans/Mission.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.io.Serializable;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Persistence;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDateTime ;
import java.time.ZoneId;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;

/**
 *
 * @author HTOUM
 */

@Entity
@Table(name = "Mission")
public class Mission implements Serializable {
    @Id
   @GeneratedValue (strategy=GenerationType.AUTO)
   @Column(name ="CodeMission" , unique = true) // valeur unique dans la BD 
    private int CodeMission ;
   
      @ManyToOne
    @JoinColumn(name="Matricule") 
    private Agent agent;
      
      @Column( name="Intitule_Mission")
      private String Intitule_Mission;
      
      @Column( name="Objectif")
      private String Objectif;
      
      @Column( name="Status" , nullable=false)
      private String Status = "En cours";
      
        
      @Column( name="DateDeh")
    @Temporal(javax.persistence.TemporalType.DATE)
      private Date DateDeb;
      
      
     @Column( name="DateFin")
    @Temporal(javax.persistence.TemporalType.DATE)
      private Date DateFin;
      
    @Column( name="NbrJours")
      private int NbrJours;
    @Column (name="Kilometrage")
     private float Kilometrage;
 
    @Column (name="Type")
     private String type;
 
    @Column (name="Etat")
    private int Etat;    
   
    
    @Column (name="ValidDirecturGeneral")
    private int ValidDirecturGeneral;    
   
    @Column (name="DateDeCreation" )
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)    
    private Date DatedeCreation = new Date();
    
    
    @Column(name="fdiver")
    private Float fdiver;
    @Column(name="fhebergement")
    private Float fhebergement;
    @Column(name="ftransport")
    private Float ftransport;
    
    @Column(name="rejet")
    private String rejet;
     @Column(name="ValidationRH")
    private int ValidationRH;
    
 
    @ManyToMany(cascade = CascadeType.ALL,fetch = FetchType.EAGER )
	@JoinTable(name = "LesVilleMission", joinColumns = { @JoinColumn(name = "CodeMission") }, inverseJoinColumns = { @JoinColumn(name = "Code_Postal")})
	public Set<ville> Les_villes;
    
    @OneToOne(fetch = FetchType.EAGER)
   @JoinColumn(name="Vehicule",referencedColumnName="id" )
    private vehicule vehicule;

   
    public int getValidDirecturGeneral() {
        return ValidDirecturGeneral;
    }

    public void setValidDirecturGeneral(int ValidDirecturGeneral) {
        this.ValidDirecturGeneral = ValidDirecturGeneral;
    }

    public Mission(int CodeMission, Agent agent, String Intitule_Mission, String Objectif, Date DateDeb, Date DateFin, int NbrJours, float Kilometrage, String type, int Etat, int ValidDirecturGeneral, Set<ville> Les_villes) {
        this.CodeMission = CodeMission;
        this.agent = agent;
        this.Intitule_Mission = Intitule_Mission;
        this.Objectif = Objectif;
        this.DateDeb = DateDeb;
        this.DateFin = DateFin;
        this.NbrJours = NbrJours;
        this.Kilometrage = Kilometrage;
        this.type = type;
        this.Etat = Etat;
        this.ValidDirecturGeneral = ValidDirecturGeneral;
        this.Les_villes = Les_villes;
    }

    
      public Mission(int CodeMission, Agent agent, String Intitule_Mission, String Objectif, Date DateDeb, Date DateFin, int NbrJours, float Kilometrage, Set<ville> Les_villes) {
        this.CodeMission = CodeMission;
        this.agent = agent;
        this.Intitule_Mission = Intitule_Mission;
        this.Objectif = Objectif;
        this.DateDeb = DateDeb;
        this.DateFin = DateFin;
        this.NbrJours = NbrJours;
        this.Kilometrage = Kilometrage;
        this.Les_villes = Les_villes;
    }

    public Mission(int CodeMission, Agent agent, String Intitule_Mission, String Objectif, Date DateDeb, Date DateFin, int NbrJours, float Kilometrage, String type, int Etat, int ValidDirecturGeneral, Float fdiver, Float fhebergement, Float ftransport, Float total, String rejet, Set<ville> Les_villes) {
        this.CodeMission = CodeMission;
        this.agent = agent;
        this.Intitule_Mission = Intitule_Mission;
        this.Objectif = Objectif;
        this.DateDeb = DateDeb;
        this.DateFin = DateFin;
        this.NbrJours = NbrJours;
        this.Kilometrage = Kilometrage;
        this.type = type;
        this.Etat = Etat;
        this.ValidDirecturGeneral = ValidDirecturGeneral;
        
        this.fdiver = fdiver;
        this.fhebergement = fhebergement;
        this.ftransport = ftransport;

        this.rejet = rejet;
        this.Les_villes = Les_villes;
    }

    
   
    public Mission() {
    }

    public Mission(int CodeMission, Agent agent, String Intitule_Mission, String Objectif, Date DateDeb, Date DateFin, int NbrJours, float Kilometrage) {
        this.CodeMission = CodeMission;
        this.agent = agent;
        this.Intitule_Mission = Intitule_Mission;
        this.Objectif = Objectif;
        this.DateDeb = DateDeb;
        this.DateFin = DateFin;
        this.NbrJours = NbrJours;
        this.Kilometrage = Kilometrage;
    }

    public Mission(int CodeMission, Agent agent, String Intitule_Mission, String Objectif, Date DateDeb, Date DateFin, int NbrJours, float Kilometrage, String type, int Etat, Set<ville> Les_villes) {
        this.CodeMission = CodeMission;
        this.agent = agent;
        this.Intitule_Mission = Intitule_Mission;
        this.Objectif = Objectif;
        this.DateDeb = DateDeb;
        this.DateFin = DateFin;
        this.NbrJours = NbrJours;
        this.Kilometrage = Kilometrage;
        this.type = type;
        this.Etat = Etat;
        this.Les_villes = Les_villes;
    }

    public Mission(int CodeMission, Agent agent, String Intitule_Mission, String Objectif, Date DateDeb, Date DateFin, int NbrJours, float Kilometrage, String type, int Etat, int ValidDirecturGeneral, Float fdiver, Float fhebergement, Float ftransport, Float total, String rejet, int ValidationRH, Set<ville> Les_villes, vehicule vehicule) {
        this.CodeMission = CodeMission;
        this.agent = agent;
        this.Intitule_Mission = Intitule_Mission;
        this.Objectif = Objectif;
        this.DateDeb = DateDeb;
        this.DateFin = DateFin;
        this.NbrJours = NbrJours;
        this.Kilometrage = Kilometrage;
        this.type = type;
        this.Etat = Etat;
        this.ValidDirecturGeneral = ValidDirecturGeneral;
        this.fdiver = fdiver;
        this.fhebergement = fhebergement;
        this.ftransport = ftransport;

        this.rejet = rejet;
        this.ValidationRH = ValidationRH;
        this.Les_villes = Les_villes;
        this.vehicule = vehicule;
    }

    public Mission(int CodeMission) {
        this.CodeMission = CodeMission;
    }

    public String getRejet() {
        return rejet;
    }

    public void setRejet(String rejet) {
        this.rejet = rejet;
    }

    public int getValidationRH() {
        return ValidationRH;
    }

    public void setValidationRH(int ValidationRH) {
        this.ValidationRH = ValidationRH;
    }
    


    
    public int getCodeMission() {
        return CodeMission;
    }

    public void setCodeMission(int CodeMission) {
        this.CodeMission = CodeMission;
    }

    public Agent getAgent() {
        return agent;
    }

    public void setAgent(Agent agent) {
        this.agent = agent;
    }

    public String getIntitule_Mission() {
        return Intitule_Mission;
    }

    public void setIntitule_Mission(String Intitule_Mission) {
        this.Intitule_Mission = Intitule_Mission;
    }

    public String getObjectif() {
        return Objectif;
    }

    public void setObjectif(String Objectif) {
        this.Objectif = Objectif;
    }

    public Date getDateDeb() {
        return DateDeb;
    }

    public void setDateDeb(Date DateDeb) {
        this.DateDeb = DateDeb;
    }

    public Date getDateFin() {
        return DateFin;
    }

    public void setDateFin(Date DateFin) {
        this.DateFin = DateFin;
    }

    public int getNbrJours() {
        return NbrJours;
    }

    public void setNbrJours(int NbrJours) {
        this.NbrJours = NbrJours;
    }

    public float getKilometrage() {
        return Kilometrage;
    }

    public void setKilometrage(float Kilometrage) {
        this.Kilometrage = Kilometrage;
    }

    public Set<ville> getLes_villes() {
        return Les_villes;
    }

    public void setLes_villes(Set<ville> Les_villes) {
        this.Les_villes = Les_villes;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getEtat() {

src/java/beans/Personnel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.io.Serializable;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 *
 * @author Mohammed Mehdi Sarray#
 */
@Entity
@Table(name = "Personnel")
@Inheritance(strategy = InheritanceType.JOINED) // Heritage

public class Personnel implements Serializable{
    
    
    private static final long serialVersionUID = 2L; 
    
   @Id
   @Column(name ="Matricule" , unique = true) // valeur unique dans la BD 
    private int Matricule;
    @Column(name ="Prenom")
   private String Pernom;
    @Column(name ="Nom")
    private String Nom;
    @Column(name ="MotDePasse")
    private String MotDePasse;
    @Column (name="email")
    private String email;

    public Personnel(int Matricule, String Pernom, String Nom, String MotDePasse, String email) {
        this.Matricule = Matricule;
        this.Pernom = Pernom;
        this.Nom = Nom;
        this.MotDePasse = MotDePasse;
        this.email = email;
    }
    

    public Personnel(int Matricule, String Pernom, String Nom, String MotDePasse) {
        this.Matricule = Matricule;
        this.Pernom = Pernom;
        this.Nom = Nom;
        this.MotDePasse = MotDePasse;
    }

    public Personnel() {
    }

    public int getMatricule() {
        return Matricule;
    }

    public void setMatricule(int Matricule) {
        this.Matricule = Matricule;
    }

    public String getPernom() {
        return Pernom;
    }

    public void setPernom(String Pernom) {
        this.Pernom = Pernom;
    }

    public String getNom() {
        return Nom;
    }

    public void setNom(String Nom) {
        this.Nom = Nom;
    }

    public String getMotDePasse() {
        return MotDePasse;
    }

    public void setMotDePasse(String MotDePasse) {
        this.MotDePasse = MotDePasse;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    

}

src/java/beans/ville.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.io.Serializable;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 *
 * @author HTOUM
 */

@Entity
@Table(name = "ville")
public class ville implements Serializable {
@Id     
 @Column(name ="Code_Postal" ) // valeur unique dans la BD 
    private int Code_Postal;
    @Column(name ="Nom")
   private String Nom;
 
  
    public ville(int Code_Postal, String Nom) {
        this.Code_Postal = Code_Postal;
        this.Nom = Nom;
    }
    
  
  
    public ville() {
    }

    public int getCode_Postal() {
        return Code_Postal;
    }

    public void setCode_Postal(int Code_Postal) {
        this.Code_Postal = Code_Postal;
    }

    public String getNom() {
        return Nom;
    }

    public void setNom(String Nom) {
        this.Nom = Nom;
    }

    @Override
    public String toString() {
        return Nom+" Code_Postal: " + Code_Postal  ;
    }

    
      
}

web/mission/FormPrintRejet.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
   <h:head>
    
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- Bootstrap Core CSS -->
<link href="../../resources/adminresource/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="../../resources/adminresource/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS-->
<link href="../../resources/adminresource/css/font-awesome.css" rel="stylesheet"/> 
<!-- //font-awesome icons CSS-->

 <!-- side nav css file -->
 <link href='../../resources/adminresource/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
 <!-- side nav css file -->
 
 <!-- js-->

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet"></link>
<!--//webfonts-->
 
<!-- Metis Menu -->
<script src="../../resources/adminresource/js/metisMenu.min.js"></script>
<script src="../../resources/adminresource/js/custom.js"></script>
<link href="../../resources/adminresource/css/custom.css" rel="stylesheet"> </link>
<!--//Metis Menu -->
   
       <meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Le Moteur Platform" />
<title>LE Moteur-sa</title>
<style>.ui-widget-content {
    border: 1px solid #d5d5d5;
    background: #fff;
    color: #222;
}
</style>
    </h:head>
    <h:body class="cbp-spmenu-push">
      
          <div class="main-content">
                  <ui:include src="topbar.xhtml" />
            
           
                 <ui:include src="leftbar.xhtml" />
              <div id="page-wrapper">
			<div class="main-page">
				<div class="forms">
<div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
      <p:panelGrid id = "panel" columns = "1"   columnClasses="ui-grid-col-4,ui-grid-col-8" layout="grid">
          
    <f:facet name="header">
        <img src="../../resources/image/logo.png" alt="Le moteur" width="200" height="100" />
    </f:facet>
                     
                         <h:outputLabel for="Matricule_Agent" value="Matricule de l'agent : #{modele_agent.agent.matricule}" />
                     
          
          
                         <h:outputLabel for="Nom_Agent" value="Nom de l'agent :#{modele_agent.agent.nom}" />
                        
          
          
                         <h:outputLabel for="Prenom_Agent" value="Prenom de l'agent : #{modele_agent.agent.pernom}" />
        
                         <h:outputLabel for="Dep_Agent" value="Departement de l'agent : #{modele_agent.DepAgent()}" />

          
          
          
                         
                         <h:outputLabel for="Code_mission" value="Code de la Mission : #{modele_agent.mission.codeMission}" />

                         
                         <h:outputLabel for="Intitule_mission" value="Intitule de la mission : #{modele_agent.mission.intitule_Mission}" />
                                                  
                         <h:outputLabel for="Date_Deb"  value="Date Depart : #{modele_agent.mission.dateDeb}" />

                         
                     
                         <h:outputLabel for="Date_Ret" value="Date Retour : #{modele_agent.mission.dateFin}" />
                         
                         <h:outputLabel for="Valide" value="Valider Par le Chef : #{modele_agent.mission.etatToString()}" />
                         
                         <h:outputLabel for="Kilometrage" value="Kilometrage : #{modele_agent.mission.kilometrage}" />
                         
                         <h:outputLabel for="Nombre_jours" value="Nombre de jours : #{modele_agent.mission.nbrJours}" />
                         
                         <h:outputLabel for="Objectif"  value="Objectif : #{modele_agent.mission.objectif}" />
                      
                         <h:outputLabel for="Immatriculation"  value="Immatriculation du vehicule : #{modele_agent.immatriculation}" />
                         <h:outputLabel for="modele"  value="Le modele du vehicule : #{modele_agent.modele}" />
                      
                         <h:outputLabel for="Motif"  value="Motif: #{modele_agent.mission.rejet}" />

                         <h:outputLabel for="Les_Villes"  value="Les Villes: #{modele_agent.villes}" />

          <h:outputLabel for="fraiseffectif"  value="Les frais effectifs: Les Frais divers #{modele_agent.mission.fdiver} Les Frais D'hebergement #{modele_agent.mission.fhebergement} Les Frais de Transport #{modele_agent.mission.ftransport}"/>

                         
                         
    </p:panelGrid>
   
</div>
                                </div>
    <p:commandButton value="Print" type="button" icon="ui-icon-print" style="display:block;margin-bottom: 20px">
    <p:printer target="panel" />
</p:commandButton>

                        </div>
              </div></div>
        
        
        <!-- side nav js -->
	<script src='../../resources/adminresource/js/SidebarNav.min.js' type='text/javascript'></script>
	<script>
      $('.sidebar-menu').SidebarNav()
    </script>
	<!-- //side nav js -->
	
	<!-- Classie --><!-- for toggle left push menu script -->
		<script src="../../resources/adminresource/js/classie.js"></script>
		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
                        
                        
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			
			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script>
	<!-- //Classie --><!-- //for toggle left push menu script -->
		
	<!--scrolling js-->
	<script src="../../resources/adminresource/js/jquery.nicescroll.js"></script>
	<script src="../../resources/adminresource/js/scripts.js"></script>
	<!--//scrolling js-->
	
	<!-- Bootstrap Core JavaScript -->
   <script src="../../resources/adminresource/js/bootstrap.js"> </script>
	<!-- //Bootstrap Core JavaScript -->
    </h:body>
</html> 

web/mission/RejetMission.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
   <h:head>
    
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- Bootstrap Core CSS -->
<link href="../../resources/adminresource/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="../../resources/adminresource/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS-->
<link href="../../resources/adminresource/css/font-awesome.css" rel="stylesheet"/> 
<!-- //font-awesome icons CSS-->

 <!-- side nav css file -->
 <link href='../../resources/adminresource/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
 <!-- side nav css file -->
 
 <!-- js-->

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet"></link>
<!--//webfonts-->
 
<!-- Metis Menu -->
<script src="../../resources/adminresource/js/metisMenu.min.js"></script>
<script src="../../resources/adminresource/js/custom.js"></script>
<link href="../../resources/adminresource/css/custom.css" rel="stylesheet"> </link>
<!--//Metis Menu -->
   
       <meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Le Moteur Platform" />
<title>LE Moteur-sa</title>
<style>.ui-widget-content {
    border: 1px solid #d5d5d5;
    background: #fff;
    color: #222;
}</style></h:head>
    <h:body class="cbp-spmenu-push">
      
          <div class="main-content">
                  <ui:include src="topbar.xhtml" />
            
           
                 <ui:include src="leftbar.xhtml" />
              <div id="page-wrapper">
			<div class="main-page">
				<div class="forms">
<div class="form-grids row widget-shadow" data-example-id="basic-forms">      
    
      <p:panelGrid id = "panel" columns = "1"   columnClasses="ui-grid-col-4,ui-grid-col-8" layout="grid">
          
    <f:facet name="header">
        <img src="../../resources/image/logo.png" alt="Le moteur" width="200" height="100" />
    </f:facet>
                     
                         <h:outputLabel for="Matricule_Agent" value="Matricule de l'agent : #{modele_agent.mission.agent.matricule}" />
                     
          
          
                         <h:outputLabel for="Nom_Agent" value="Nom de l'agent :#{modele_agent.mission.agent.nom}" />
                        
                         
          
                         <h:outputLabel for="Prenom_Agent" value="Prenom de l'agent : #{modele_agent.mission.agent.pernom}" />
        
                         <h:outputLabel for="Dep_Agent" value="Departement de l'agent : #{modele_agent.departement}" />

          
          
          
                         
                         <h:outputLabel for="Code_mission" value="Code de la Mission : #{modele_agent.mission.codeMission}" />

                         
                         <h:outputLabel for="Intitule_mission" value="Intitule de la mission : #{modele_agent.mission.intitule_Mission}" />
                                                  
                         <h:outputLabel for="Date_Deb"  value="Date Depart : #{modele_agent.mission.dateDeb}" />

                         
                     
                         <h:outputLabel for="Date_Ret" value="Date Retour : #{modele_agent.mission.dateFin}" />
                         
                         <h:outputLabel for="Valide" value="Valider Par le Chef : #{modele_agent.mission.etatToString()}" />
                         
                         <h:outputLabel for="Kilometrage" value="Kilometrage : #{modele_agent.mission.kilometrage}" />
                         
                         <h:outputLabel for="Nombre_jours" value="Nombre de jours : #{modele_agent.mission.nbrJours}" />
                         
                         <h:outputLabel for="Objectif"  value="Objectif : #{modele_agent.mission.objectif}" />
                      
                         <h:outputLabel for="Les_Villes"  value="Les Villes: #{modele_agent.villes}" />

       

                         
    </p:panelGrid>    
        
</div>
                                </div> 
             <h:form>             
       <div class="form-group"> <p:outputLabel  value="Motif du rejet: "> </p:outputLabel></div> 
       <div class="form-group">   <p:inputText class="form-control" value="#{modele_agent.rejet}" placeholder="Motif" required="true" > </p:inputText> </div> 

        <div class="form-group">   <p:commandButton value="Confirmer" id="ajax"  actionListener="#{modele_agent.rejet()}" class="btn btn-default" ajax="false"/> </div> 
    </h:form>         </div>
              </div></div>
        
        
        <!-- side nav js -->
	<script src='../../resources/adminresource/js/SidebarNav.min.js' type='text/javascript'></script>
	<script>
      $('.sidebar-menu').SidebarNav()
    </script>
	<!-- //side nav js -->
	
	<!-- Classie --><!-- for toggle left push menu script -->
		<script src="../../resources/adminresource/js/classie.js"></script>
		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
                        
                        
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			
			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script>
	<!-- //Classie --><!-- //for toggle left push menu script -->
		
	<!--scrolling js-->
	<script src="../../resources/adminresource/js/jquery.nicescroll.js"></script>
	<script src="../../resources/adminresource/js/scripts.js"></script>
	<!--//scrolling js-->
	
	<!-- Bootstrap Core JavaScript -->
   <script src="../../resources/adminresource/js/bootstrap.js"> </script>
	<!-- //Bootstrap Core JavaScript -->
    </h:body>
</html> 