src/java/beans/BulletinMensuel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 *
 * @author Mohammed Mehdi Sarray#
 */
@Entity
@Table(name = "BulletinMensuel")
public class BulletinMensuel implements Serializable{
    
     private static final long serialVersionUID = 13225L;
    
    
    @Id
   @GeneratedValue (strategy=GenerationType.AUTO)
   @Column(name ="id")
    private int Id; 
    
    @Column(name="Matricule_Assurer")
    private int Matricule ;   
    
    @Column(name ="Numero_de_bulletin")
    private int num_bulletin;
    @Column(name ="Montant_prescrit")
    private float Montant_prescrit;
    @Column(name ="Date_transmit")
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date Date_transmit ;
    @Column(name ="Malade")
    private String Malade;
    @Column(name ="Date_Remboursement")
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date Date_Remboursement;
    @Column(name ="Montant_remboursement")
    private float Montant_remboursement;
    @Column(name ="Observation")
    private String Observation;
    @Column (name="DateDeCreation" )
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)    
    private Date DatedeCreation = new Date();
     
    @ManyToOne
    @JoinColumn(name="assurer", nullable=false)
    private Assurer assurer;

    public int getMatricule() {
        return Matricule;
    }

    public void setMatricule(int Matricule) {
        this.Matricule = Matricule;
    }


    public int getNum_bulletin() {
        return num_bulletin;
    }

    public void setNum_bulletin(Integer num_bulletin) {
        this.num_bulletin = num_bulletin;
    }

    public float getMontant_prescrit() {
        return Montant_prescrit;
    }

    public void setMontant_prescrit(Float Montant_prescrit) {
        this.Montant_prescrit = Montant_prescrit;
    }

    public Date getDate_transmit() {
        return Date_transmit;
    }

    public void setDate_transmit(Date Date_transmit) {
        this.Date_transmit = Date_transmit;
    }

    public String getMalade() {
        return Malade;
    }

    public void setMalade(String Malade) {
        this.Malade = Malade;
    }

    public Date getDate_Remboursement() {
        return Date_Remboursement;
    }

    public void setDate_Remboursement(Date Date_Remboursement) {
        this.Date_Remboursement = Date_Remboursement;
    }

    public float getMontant_remboursement() {
        return Montant_remboursement;
    }

    public void setMontant_remboursement(Float Montant_remboursement) {
        this.Montant_remboursement = Montant_remboursement;
    }

    public String getObservation() {
        return Observation;
    }

    public void setObservation(String Observation) {
        this.Observation = Observation;
    }

    public int getId() {
        return Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    public Assurer getAssurer() {
        return assurer;
    }

    public void setAssurer(Assurer assurer) {
        this.assurer = assurer;
    }

    public Date getDatedeCreation() {
        return DatedeCreation;
    }

    public void setDatedeCreation(Date DatedeCreation) {
        this.DatedeCreation = DatedeCreation;
    }
            

    




}

src/java/beans/Personnel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.io.Serializable;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 *
 * @author Mohammed Mehdi Sarray#
 */
@Entity
@Table(name = "Personnel")
@Inheritance(strategy = InheritanceType.JOINED) // Heritage

public class Personnel implements Serializable{
    
    
    private static final long serialVersionUID = 2L; 
    
   @Id
   @Column(name ="Matricule" , unique = true) // valeur unique dans la BD 
    private int Matricule;
    @Column(name ="Prenom")
   private String Pernom;
    @Column(name ="Nom")
    private String Nom;
    @Column(name ="MotDePasse")
    private String MotDePasse;
    @Column (name="email")
    private String email;

    public Personnel(int Matricule, String Pernom, String Nom, String MotDePasse, String email) {
        this.Matricule = Matricule;
        this.Pernom = Pernom;
        this.Nom = Nom;
        this.MotDePasse = MotDePasse;
        this.email = email;
    }
    

    public Personnel(int Matricule, String Pernom, String Nom, String MotDePasse) {
        this.Matricule = Matricule;
        this.Pernom = Pernom;
        this.Nom = Nom;
        this.MotDePasse = MotDePasse;
    }

    public Personnel() {
    }

    public int getMatricule() {
        return Matricule;
    }

    public void setMatricule(int Matricule) {
        this.Matricule = Matricule;
    }

    public String getPernom() {
        return Pernom;
    }

    public void setPernom(String Pernom) {
        this.Pernom = Pernom;
    }

    public String getNom() {
        return Nom;
    }

    public void setNom(String Nom) {
        this.Nom = Nom;
    }

    public String getMotDePasse() {
        return MotDePasse;
    }

    public void setMotDePasse(String MotDePasse) {
        this.MotDePasse = MotDePasse;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    

}

src/java/beans/ville.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.io.Serializable;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 *
 * @author HTOUM
 */

@Entity
@Table(name = "ville")
public class ville implements Serializable {
@Id     
 @Column(name ="Code_Postal" ) // valeur unique dans la BD 
    private int Code_Postal;
    @Column(name ="Nom")
   private String Nom;
 
  
    public ville(int Code_Postal, String Nom) {
        this.Code_Postal = Code_Postal;
        this.Nom = Nom;
    }
    
  
  
    public ville() {
    }

    public int getCode_Postal() {
        return Code_Postal;
    }

    public void setCode_Postal(int Code_Postal) {
        this.Code_Postal = Code_Postal;
    }

    public String getNom() {
        return Nom;
    }

    public void setNom(String Nom) {
        this.Nom = Nom;
    }

    @Override
    public String toString() {
        return Nom+" Code_Postal: " + Code_Postal  ;
    }

    
      
}

src/main/java/com/sodecodigo/controller/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sodecodigo.controller;

import com.sodecodigo.controller.UsuarioController;
import com.sodecodigo.controller.AbstractController;
import com.sodecodigo.dao.UsuarioDao;
import com.sodecodigo.model.Usuario;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

@RequestScoped
@ManagedBean
public class LoginController extends AbstractController {

    @ManagedProperty(value = UsuarioController.INJECTION_NAME)
    private UsuarioController usuarioController;

    private String loginOrEmail;
    private String password;

    public void setUsuarioController(UsuarioController usuarioController) {
        this.usuarioController = usuarioController;
    }

    public String getLogin() {
        return loginOrEmail;
    }

    public void setLogin(String login) {
        this.loginOrEmail = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    private Usuario isValidLogin(String loginOrEmail, String password) {
         Usuario user;
         
        if(isEmail(loginOrEmail)){
            user = new UsuarioDao().findByEmail(loginOrEmail);
        }else{
            user = new UsuarioDao().findByLogin(loginOrEmail);
        }
        
        if (user == null || !password.equals(user.getSenha())) {
            return null;
        }
        return user;
    }
    
    private boolean isEmail(String value){
        return value.contains("@");
    }

    public String entrar() {
        Usuario user = isValidLogin(loginOrEmail, password);

        if (user != null) {
            usuarioController.setUser(user);
            FacesContext context = FacesContext.getCurrentInstance();
            HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
            request.getSession().setAttribute("user", user);
            return "index.xhtml";
        }
        displayErrorMessage("Check your login/password");
        return null;
    }

}

web/assurance/NouveauBulletin.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <f:view contentType="text/html">
    <h:head>
              <style> element.style { width: auto; height: auto; visibility: visible; z-index: 1010; display: block; } .ui-dialog { top: 40% !important; left: 50%!important; } </style>

        <title>Agent</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- Bootstrap Core CSS -->
<link href="../../resources/adminresource/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="../../resources/adminresource/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS-->
<link href="../../resources/adminresource/css/font-awesome.css" rel="stylesheet"/> 
<!-- //font-awesome icons CSS-->

 <!-- side nav css file -->
 <link href='../../resources/adminresource/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
 <!-- side nav css file -->
 
 <!-- js-->
<script src="../../resources/adminresource/js/modernizr.custom.js"></script>

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet"></link>
<!--//webfonts-->
 
<!-- Metis Menu -->
<script src="../../resources/adminresource/js/metisMenu.min.js"></script>
<script src="../../resources/adminresource/js/custom.js"></script>
<link href="../../resources/adminresource/css/custom.css" rel="stylesheet"> </link>
<!--//Metis Menu -->
    <style>
 

    </style>
    </h:head>
    <h:body class="cbp-spmenu-push">
      
          <div class="main-content">
          
                 <ui:include src="topbar.xhtml" />
            
           
                 <ui:include src="leftbar.xhtml" />
            
        <div id="page-wrapper">
			<div class="main-page">
				<div class="forms">       
                                        <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
						<div class="form-title">
							<h4>Liste de mes bulletins :</h4>
						</div>
						<div class="form-body">
                                                  <div class="form-group">
               
                                                             <p:dataTable  var="bulletin" emptyMessage="Vous n'avez aucun nouveau bulletin." value="#{modele_assurer.ListernouveauBulletin()}" rows="9" paginator="true"  >
                    
                                                               <p:column headerText="date transmit">
                                                                     <h:outputText value="#{bulletin.date_transmit}"  />
                                                                  </p:column>   
                                                                 <p:column headerText="date_Remboursement" >
                                                                     <h:outputText value="#{bulletin.date_Remboursement}"  />
                                                              </p:column> 
                                                        <p:column headerText="montant Prescrit" >
                                                            <h:outputText value="#{bulletin.montant_prescrit}" />
                                                          </p:column>  
                                                         <p:column headerText="montant remboursement" >
                                                             <h:outputText value="#{bulletin.montant_remboursement}" />
                                                          </p:column>  
                                                           
                                                         
                                                             </p:dataTable> 
                                                                 
                                                         </div> 
                                                        
                                                            
                                                             
                                             
                                                          
						</div>
					</div>
                                        
                                        
                                        
                                        
                                        
                                        
                                        
					</div>
                            </div>
            </div>
        </div>
        
            
            
    
        
        <!-- side nav js -->
	<script src='../../resources/adminresource/js/SidebarNav.min.js' type='text/javascript'></script>
	<script>
      $('.sidebar-menu').SidebarNav()
    </script>
	<!-- //side nav js -->
	
	<!-- Classie --><!-- for toggle left push menu script -->
		<script src="../../resources/adminresource/js/classie.js"></script>
		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
                        
                        
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			
			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script>
	<!-- //Classie --><!-- //for toggle left push menu script -->
		
	<!--scrolling js-->
	<script src="../../resources/adminresource/js/jquery.nicescroll.js"></script>
	<script src="../../resources/adminresource/js/scripts.js"></script>
	<!--//scrolling js-->
	
	<!-- Bootstrap Core JavaScript -->
   <script src="../../resources/adminresource/js/bootstrap.js"> </script>
	<!-- //Bootstrap Core JavaScript -->
    </h:body>
        </f:view>
</html> 

web/assurance/historique.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <f:view contentType="text/html">
    <h:head>
              <style> element.style { width: auto; height: auto; visibility: visible; z-index: 1010; display: block; } .ui-dialog { top: 40% !important; left: 50%!important; } </style>

        <title>Agent</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- Bootstrap Core CSS -->
<link href="../../resources/adminresource/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="../../resources/adminresource/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS-->
<link href="../../resources/adminresource/css/font-awesome.css" rel="stylesheet"/> 
<!-- //font-awesome icons CSS-->

 <!-- side nav css file -->
 <link href='../../resources/adminresource/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
 <!-- side nav css file -->
 
 <!-- js-->
<script src="../../resources/adminresource/js/modernizr.custom.js"></script>

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet"></link>
<!--//webfonts-->
 
<!-- Metis Menu -->
<script src="../../resources/adminresource/js/metisMenu.min.js"></script>
<script src="../../resources/adminresource/js/custom.js"></script>
<link href="../../resources/adminresource/css/custom.css" rel="stylesheet"> </link>
<!--//Metis Menu -->
    <style>
 

    </style>
    </h:head>
    <h:body class="cbp-spmenu-push">
      
          <div class="main-content">
          
                 <ui:include src="topbar.xhtml" />
            
           
                 <ui:include src="leftbar.xhtml" />
            
        <div id="page-wrapper">
			<div class="main-page">
				<div class="forms">       
                                        <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
						<div class="form-title">
							<h4>Liste de mes bulletins :</h4>
						</div>
						<div class="form-body">
                                                  <div class="form-group">
               
                                                      <p:dataTable  var="bulletin" emptyMessage="Vous n'avez aucun nouveau bulletin." value="#{modele_assurer.ListerHistoriqueBulletin()}" rows="9" paginator="true"  >
                    
                                         <p:column headerText="date transmit">
                                                                     <h:outputText value="#{bulletin.date_transmit}"  />
                                                                  </p:column>   
                                                                 <p:column headerText="date_Remboursement" >
                                                                     <h:outputText value="#{bulletin.date_Remboursement}"  />
                                                              </p:column> 
                                                        <p:column headerText="montant Prescrit" >
                                                            <h:outputText value="#{bulletin.montant_prescrit}" />
                                                          </p:column>  
                                                         <p:column headerText="montant remboursement" >
                                                             <h:outputText value="#{bulletin.montant_remboursement}" />
                                                          </p:column>  
                                                           
                                                         
                                                             </p:dataTable> 
                                                                 
                                                         </div> 
                                                        
                                                            
                                                             
                                             
                                                          
						</div>
					</div>
                                        
                                        
                                        
                                        
                                        
                                        
                                        
					</div>
                            </div>
            </div>
        </div>
        
            
            
    
        
        <!-- side nav js -->
	<script src='../../resources/adminresource/js/SidebarNav.min.js' type='text/javascript'></script>
	<script>
      $('.sidebar-menu').SidebarNav()
    </script>
	<!-- //side nav js -->
	
	<!-- Classie --><!-- for toggle left push menu script -->
		<script src="../../resources/adminresource/js/classie.js"></script>
		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
                        
                        
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			
			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script>
	<!-- //Classie --><!-- //for toggle left push menu script -->
		
	<!--scrolling js-->
	<script src="../../resources/adminresource/js/jquery.nicescroll.js"></script>
	<script src="../../resources/adminresource/js/scripts.js"></script>
	<!--//scrolling js-->
	
	<!-- Bootstrap Core JavaScript -->
   <script src="../../resources/adminresource/js/bootstrap.js"> </script>
	<!-- //Bootstrap Core JavaScript -->
    </h:body>
        </f:view>
</html> 

web/assurance/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f = "http://java.sun.com/jsf/core"
      >
    <h:head>
        <title>Administrator</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <!-- Bootstrap Core CSS -->
<link href="../../resources/adminresource/css/bootstrap.css" rel='stylesheet' type='text/css' />

<!-- Custom CSS -->
<link href="../../resources/adminresource/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS-->
<link href="../../resources/adminresource/css/font-awesome.css" rel="stylesheet"> </link>
<!-- //font-awesome icons CSS-->

 <!-- side nav css file -->
 <link href='../../resources/adminresource/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
 <!-- side nav css file -->
 
 <!-- js-->
<script src="../../resources/adminresource/js/modernizr.custom.js"></script>

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet"></link>
<!--//webfonts-->
 
<!-- Metis Menu -->
<script src="../../resources/adminresource/js/metisMenu.min.js"></script>
<script src="../../resources/adminresource/js/custom.js"></script>
<link href="../../resources/adminresource/css/custom.css" rel="stylesheet"> </link>
<!--//Metis Menu -->
<style>
    
    .ui-button {
        border: none;
    outline: none;
    cursor: pointer;
    color: #fff;
    background: #F2B33F;
    width: 40%;
    padding: .6em 1em;
    font-size: 1em;
    margin: 0.5em auto 0;
    display: block;
	transition: 0.5s all;
	-webkit-transition: 0.5s all;
	-moz-transition: 0.5s all;
	-ms-transition: 0.5s all;
	-o-transition: 0.5s all;
    }
    .ui-button:hover{
     background: #337ab7;
    }
    .login-page input.user,.login-page input.lock {
        font-size: 1em;
    padding: 14px 15px 14px 37px;
    width: 100%;
    color: #A8A8A8;
    outline: none;
    border: 1px solid #D3D3D3;
    background: #FFFFFF;
    margin: 0em 0em 1.5em 0em;
    }
    
       
    .login-page input.user {
    background: url(../../resources/adminresource/images/user.png)no-repeat 8px 16px #fff;
    }
    .login-page input.lock {
    background: url(../../resources/adminresource/images/lock.png)no-repeat 8px 16px #fff;
    }
</style>
    
    </h:head>
    <h:body>
        	<!-- main content start-->
                <div class="main-content">
		<div id="page-wrapper">
			<div class="main-page login-page ">
				<h2 class="title1">Login</h2>
				<div class="widget-shadow">
					<div class="login-body">
                                            <h:form>
                     <p:messages id="messages" showDetail="true" closable="true">
        <p:autoUpdate />
    </p:messages>
                                                <p:inputText  value="#{modele_assurer.userConnection.matricule}" required="true" styleClass="user" placeholder="Enter votre Matricule"/>
                                                <p:password value="#{modele_assurer.userConnection.motDePasse}" required="true"  styleClass="lock" placeholder="Enter votre Mot de pass"/>
							<div class="forgot-grid">
                                                          
								<div class="clearfix"> </div>
							</div>
							<p:commandButton value="Login" action="#{modele_assurer.logmein()}"
                                                                 ajax="true"/>
							
						</h:form>
					</div>
				</div>
				
			</div>
		</div>
		<!--footer-->
		<div class="footer">
		   <p>  Portail Assurance |  <a href="../index.xhtml" target="_blank">Le Moteur-sa</a></p>		</div>
                 <!--//footer-->
	</div>
                <!--scrolling js-->
	<script src="../../resources/adminresource/../resources/adminresource/js/jquery.nicescroll.js"></script>
	<script src="../../resources/adminresource/adminresource/js/scripts.js"></script>
	<!--//scrolling js-->
	
	<!-- Bootstrap Core JavaScript -->
   <script src="../../resources/adminresource/js/bootstrap.js"> </script>
	<!-- //Bootstrap Core JavaScript -->
    </h:body>
    
</html>

web/assurance/topbar.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    

        <!--left-fixed -navigation-->		
		<!-- header-starts -->
		<!--left-fixed -navigation-->		
		<!-- header-starts -->
		<div class="sticky-header header-section ">
			<div class="header-left">
				
				<!--toggle button start-->
				<button id="showLeftPush"><i class="fa fa-bars"></i></button>
				<!--toggle button end-->
				<div class="profile_details_left"><!--notifications of menu start -->
					
					<div class="clearfix"> </div>
				</div>
				<!--notification menu end -->
				<div class="clearfix"> </div>
			</div>
			<div class="header-right">
				
				
				
				
				<div class="profile_details">		
					<ul>
						<li class="dropdown profile_details_drop">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<div class="profile_img">	

									<div class="user-name">
                                                                            <p style="white-space: nowrap">  #{modele_assurer.userConnection.nom} #{modele_assurer.userConnection.pernom} </p>
                                                                            <!--<p:outputLabel value="" styleClass="user-name"></p:outputLabel> -->
										<span>Assurer</span>
									</div>
									
									<div class="clearfix"></div>	
								</div>	
							</a>
                                                    <h:form>	<h:commandLink action="#{modele_assurer.logout()}" value="Logout" styleClass="fa fa-sign-out"/> </h:form>
						</li>
					</ul>
						
				</div>
				<div class="clearfix"> </div>				
			</div>
			<div class="clearfix"> </div>	
		</div>
		<!-- //header-ends -->
    
    	
       
          
        </ui:composition>